HEAD_START_ROW = 2
HEAD_START_COLUMN = 0
CONTEST_START_ROW = 4
CONTEST_START_COLUMN = 0
QUESTION_START_ROW = 4
QUESTION_START_COLUMN = 6
PENDING_QUESTION_START_ROW = 3
PENDING_QUESTION_START_COLUMN = 7
